### ISSUE TITLE
Single Calendar design issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#102]
Woo Commerce Version - 8.0.1
WordPress Version - 6.2.2
Plugin Version - 3.1.2
Description -
Single Calendar design issue
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/179147a1-a480-4926-ab5e-02e41d0660b9)

**Comment by rishabhmwb** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Still an issue:
When Booking Unit is chosen to "days"
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/f0bfc4b8-efe1-49c4-a81a-de4bc387f2f7)
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/a1bcf350-58b0-42ba-a627-2b86dcf8195c)

**Comment by Sukirti-CEDCOSS** [comment]
Change the Design of the calendar :
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/fdfbc943-3917-4973-bc2e-8ba4e88a790b)
