### ISSUE TITLE
Slot timing issue in single calendar.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#103]
**Woo Commerce Version** - 8.0.2
**WordPress Version** - 6.2.2
**Plugin Version** - 3.1.2
**Description** - Slot timing issue in single calendar. Please add notification on time slot

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/15530a6d-6916-4ec4-bdc9-634fef6cfcee)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/959da3da-e0f8-4a27-b671-d4be9b88ca07)

**Comment by rishabhmwb** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Still an issue:
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/cc71096f-3dee-422a-b291-a2b6762874d8)

**Comment by Sukirti-CEDCOSS** [comment]
verified
